"""
RepoLens AI — Report Builder
Assembles the final Markdown report from all analysis components.
"""

from datetime import datetime, timezone
from .scoring import get_score_grade, get_score_emoji


def build_full_report(
    repo_data: dict,
    stack: list[str],
    readme_analysis: dict,
    structure_analysis: dict,
    scores: dict,
    security_items: list[dict],
    repo_info: dict | None = None,
    ai_report: str = "",
) -> str:
    """Build the complete Markdown report."""

    owner = repo_data["owner"]
    repo = repo_data["repo"]
    files = repo_data["files"]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    report_parts = []

    # ── Header ───────────────────────────────────────────────────────
    report_parts.append(f"""# 🧠 RepoLens AI Report

**Repository:** [{owner}/{repo}]({repo_data['url']})
**Generated:** {timestamp}
**Files Analyzed:** {len(files)}

---
""")

    # ── Score Dashboard ──────────────────────────────────────────────
    overall = scores["overall"]
    grade = get_score_grade(overall)
    emoji = get_score_emoji(overall)

    report_parts.append(f"""## 📊 Score Dashboard

| Metric | Score | Grade |
|--------|-------|-------|
| {get_score_emoji(scores['documentation'])} Documentation | {scores['documentation']}/100 | {get_score_grade(scores['documentation'])} |
| {get_score_emoji(scores['structure'])} Structure | {scores['structure']}/100 | {get_score_grade(scores['structure'])} |
| {get_score_emoji(scores['maintainability'])} Maintainability | {scores['maintainability']}/100 | {get_score_grade(scores['maintainability'])} |
| {get_score_emoji(scores['product_readiness'])} Product-Readiness | {scores['product_readiness']}/100 | {get_score_grade(scores['product_readiness'])} |
| **{emoji} Overall** | **{overall}/100** | **{grade}** |

---
""")

    # ── Repository Metadata ──────────────────────────────────────────
    if repo_info:
        report_parts.append(f"""## 📦 Repository Info

- **Language:** {repo_info.get('language', 'N/A')}
- **Stars:** ⭐ {repo_info.get('stars', 0):,}
- **Forks:** 🍴 {repo_info.get('forks', 0):,}
- **Open Issues:** {repo_info.get('open_issues', 0)}
- **License:** {repo_info.get('license', 'N/A')}
- **Last Updated:** {repo_info.get('updated_at', 'N/A')[:10]}
- **Topics:** {', '.join(repo_info.get('topics', [])) or 'None'}
- **Archived:** {'Yes ⚠️' if repo_info.get('archived') else 'No'}

---
""")

    # ── Tech Stack ───────────────────────────────────────────────────
    if stack:
        report_parts.append("## 🏗️ Detected Tech Stack\n\n")
        for tech in stack:
            report_parts.append(f"- {tech}")
        report_parts.append("\n---\n")

    # ── Files Detected ───────────────────────────────────────────────
    report_parts.append("## 📁 Files Detected\n\n")
    for f in sorted(files.keys()):
        report_parts.append(f"- `{f}`")
    report_parts.append("\n---\n")

    # ── README Quality ───────────────────────────────────────────────
    report_parts.append(f"""## 📝 README Quality

**Score:** {readme_analysis['score']}/100

| Check | Status |
|-------|--------|
""")
    for key, check in readme_analysis["checks"].items():
        status = "✅" if check["found"] else "❌"
        report_parts.append(f"| {check['label']} | {status} |")

    report_parts.append("\n---\n")

    # ── Project Structure ────────────────────────────────────────────
    report_parts.append(f"""## 🗂️ Project Structure

**Score:** {structure_analysis['score']}/100

| File | Status | Points |
|------|--------|--------|
""")
    for file_name, check in structure_analysis["checks"].items():
        status = "✅" if check["exists"] else "❌"
        report_parts.append(
            f"| {check['label']} | {status} | {check['earned']}/{check['weight']} |"
        )

    report_parts.append("\n---\n")

    # ── Security Checklist ───────────────────────────────────────────
    report_parts.append("## 🔒 Security & Config Checklist\n\n")
    for item in security_items:
        icon = "✅" if item["present"] else "⚠️"
        report_parts.append(f"- {icon} {item['description']}")
    report_parts.append("\n---\n")

    # ── AI Analysis ──────────────────────────────────────────────────
    if ai_report:
        report_parts.append(f"""## 🤖 AI Maintainer Analysis

{ai_report}

---
""")

    # ── Footer ───────────────────────────────────────────────────────
    report_parts.append(f"""## 📎 Generated by

**RepoLens AI** — AI-powered GitHub repository auditor
Built with Python, Streamlit, and OpenAI
""")

    return "\n".join(report_parts)
